default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: btracker
  adapter: postgresql
  encoding: unicode
  port: 4556
  host : localhost
  username: postgres
  password: meshu

test:
  <<: *default
  database: btracker-test 
  host : localhost
  port: 4556
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: meshu
